#!/bin/bash

export DB_USER=$(cat $POSTGRES_USER_FILE)
export DB_PASS=$(cat $POSTGRES_PASSWORD_FILE)

export REDIS_PASSWORD=$(cat $REDIS_PASSWORD_FILE)

export INFLUXDB2_TOKEN=$(cat $INFLUXDB2_TOKEN_FILE)

export S3_REGION=$(cat $S3_REGION_FILE)
export S3_ACCESS_KEY=$(cat $S3_ACCESS_KEY_FILE)
export S3_SECRET_KEY=$(cat $S3_SECRET_KEY_FILE)
export S3_ENDPOINT=$(cat $S3_ENDPOINT_FILE)
export S3_UPLOAD_BUCKET=$(cat $S3_UPLOAD_BUCKET_FILE)

export MAILGUN_BASE_URL=$(cat $MAILGUN_BASE_URL_FILE)
export MAILGUN_API_KEY=$(cat $MAILGUN_API_KEY_FILE)
export MAILGUN_DOMAIN=$(cat $MAILGUN_DOMAIN_FILE)

exec java -jar /app/ommnia-system-api.jar
